[package]
name = "futures-many"
version = "0.1.0"
authors = ["James Laver <james.laver@gmail.com>"]
edition = "2018"

[dependencies]
futures-core = "0.3"
futures-micro = "0.1"
primitive_traits = "0.2"
rle-bitset = { path = "../rle-bitset" }